//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedidoresModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medidore
    {
        public int Id { get; set; }
        public Nullable<int> NumMedidor { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<double> Consumo { get; set; }
    }
}
